// Canonical book metadata used by import-bible.mjs.
// VPL files only carry the 3-letter book code; localized name + abbreviation
// + canonical number + testament must come from this table.
//
// Codes follow eBible.org's variant of USFM (used in *_vpl.txt):
//   JOH not JHN, MAR not MRK, PHI not PHP, SOL not SNG, 1JO/2JO/3JO not 1JN/2JN/3JN.

export const BOOK_CODES = [
  // Old Testament (39)
  'GEN', 'EXO', 'LEV', 'NUM', 'DEU',
  'JOS', 'JDG', 'RUT', '1SA', '2SA',
  '1KI', '2KI', '1CH', '2CH', 'EZR',
  'NEH', 'EST', 'JOB', 'PSA', 'PRO',
  'ECC', 'SOL', 'ISA', 'JER', 'LAM',
  'EZE', 'DAN', 'HOS', 'JOE', 'AMO',
  'OBA', 'JON', 'MIC', 'NAH', 'HAB',
  'ZEP', 'HAG', 'ZEC', 'MAL',
  // New Testament (27)
  'MAT', 'MAR', 'LUK', 'JOH', 'ACT',
  'ROM', '1CO', '2CO', 'GAL', 'EPH',
  'PHI', 'COL', '1TH', '2TH', '1TI',
  '2TI', 'TIT', 'PHM', 'HEB', 'JAM',
  '1PE', '2PE', '1JO', '2JO', '3JO',
  'JUD', 'REV',
];

export const BOOK_NUMBER = Object.fromEntries(BOOK_CODES.map((c, i) => [c, i + 1]));
export const BOOK_TESTAMENT = Object.fromEntries(BOOK_CODES.map((c, i) => [c, i < 39 ? 'OT' : 'NT']));

// Localized names per language. de used for both Luther 1912 and Schlachter 1951.
export const BOOK_NAMES = {
  ru: {
    GEN: { name: 'Бытие',                   abbreviation: 'Быт' },
    EXO: { name: 'Исход',                   abbreviation: 'Исх' },
    LEV: { name: 'Левит',                   abbreviation: 'Лев' },
    NUM: { name: 'Числа',                   abbreviation: 'Чис' },
    DEU: { name: 'Второзаконие',            abbreviation: 'Втор' },
    JOS: { name: 'Иисус Навин',             abbreviation: 'Нав' },
    JDG: { name: 'Книга Судей',             abbreviation: 'Суд' },
    RUT: { name: 'Руфь',                    abbreviation: 'Руфь' },
    '1SA': { name: '1-я Царств',            abbreviation: '1Цар' },
    '2SA': { name: '2-я Царств',            abbreviation: '2Цар' },
    '1KI': { name: '3-я Царств',            abbreviation: '3Цар' },
    '2KI': { name: '4-я Царств',            abbreviation: '4Цар' },
    '1CH': { name: '1-я Паралипоменон',     abbreviation: '1Пар' },
    '2CH': { name: '2-я Паралипоменон',     abbreviation: '2Пар' },
    EZR: { name: 'Ездра',                   abbreviation: 'Езд' },
    NEH: { name: 'Неемия',                  abbreviation: 'Неем' },
    EST: { name: 'Есфирь',                  abbreviation: 'Есф' },
    JOB: { name: 'Иов',                     abbreviation: 'Иов' },
    PSA: { name: 'Псалтирь',                abbreviation: 'Пс' },
    PRO: { name: 'Притчи',                  abbreviation: 'Притч' },
    ECC: { name: 'Екклесиаст',              abbreviation: 'Еккл' },
    SOL: { name: 'Песнь Песней',            abbreviation: 'Песн' },
    ISA: { name: 'Исаия',                   abbreviation: 'Ис' },
    JER: { name: 'Иеремия',                 abbreviation: 'Иер' },
    LAM: { name: 'Плач Иеремии',            abbreviation: 'Плач' },
    EZE: { name: 'Иезекииль',               abbreviation: 'Иез' },
    DAN: { name: 'Даниил',                  abbreviation: 'Дан' },
    HOS: { name: 'Осия',                    abbreviation: 'Ос' },
    JOE: { name: 'Иоиль',                   abbreviation: 'Иоиль' },
    AMO: { name: 'Амос',                    abbreviation: 'Амос' },
    OBA: { name: 'Авдий',                   abbreviation: 'Авд' },
    JON: { name: 'Иона',                    abbreviation: 'Иона' },
    MIC: { name: 'Михей',                   abbreviation: 'Мих' },
    NAH: { name: 'Наум',                    abbreviation: 'Наум' },
    HAB: { name: 'Аввакум',                 abbreviation: 'Авв' },
    ZEP: { name: 'Софония',                 abbreviation: 'Соф' },
    HAG: { name: 'Аггей',                   abbreviation: 'Агг' },
    ZEC: { name: 'Захария',                 abbreviation: 'Зах' },
    MAL: { name: 'Малахия',                 abbreviation: 'Мал' },
    MAT: { name: 'От Матфея',               abbreviation: 'Мф' },
    MAR: { name: 'От Марка',                abbreviation: 'Мк' },
    LUK: { name: 'От Луки',                 abbreviation: 'Лк' },
    JOH: { name: 'От Иоанна',               abbreviation: 'Ин' },
    ACT: { name: 'Деяния',                  abbreviation: 'Деян' },
    ROM: { name: 'Римлянам',                abbreviation: 'Рим' },
    '1CO': { name: '1-е Коринфянам',        abbreviation: '1Кор' },
    '2CO': { name: '2-е Коринфянам',        abbreviation: '2Кор' },
    GAL: { name: 'Галатам',                 abbreviation: 'Гал' },
    EPH: { name: 'Ефесянам',                abbreviation: 'Еф' },
    PHI: { name: 'Филиппийцам',             abbreviation: 'Флп' },
    COL: { name: 'Колоссянам',              abbreviation: 'Кол' },
    '1TH': { name: '1-е Фессалоникийцам',   abbreviation: '1Фес' },
    '2TH': { name: '2-е Фессалоникийцам',   abbreviation: '2Фес' },
    '1TI': { name: '1-е Тимофею',           abbreviation: '1Тим' },
    '2TI': { name: '2-е Тимофею',           abbreviation: '2Тим' },
    TIT: { name: 'Титу',                    abbreviation: 'Тит' },
    PHM: { name: 'Филимону',                abbreviation: 'Флм' },
    HEB: { name: 'Евреям',                  abbreviation: 'Евр' },
    JAM: { name: 'Иакова',                  abbreviation: 'Иак' },
    '1PE': { name: '1-е Петра',             abbreviation: '1Пет' },
    '2PE': { name: '2-е Петра',             abbreviation: '2Пет' },
    '1JO': { name: '1-е Иоанна',            abbreviation: '1Ин' },
    '2JO': { name: '2-е Иоанна',            abbreviation: '2Ин' },
    '3JO': { name: '3-е Иоанна',            abbreviation: '3Ин' },
    JUD: { name: 'Иуды',                    abbreviation: 'Иуд' },
    REV: { name: 'Откровение',              abbreviation: 'Откр' },
  },
  de: {
    GEN: { name: '1. Mose',                 abbreviation: '1.Mose' },
    EXO: { name: '2. Mose',                 abbreviation: '2.Mose' },
    LEV: { name: '3. Mose',                 abbreviation: '3.Mose' },
    NUM: { name: '4. Mose',                 abbreviation: '4.Mose' },
    DEU: { name: '5. Mose',                 abbreviation: '5.Mose' },
    JOS: { name: 'Josua',                   abbreviation: 'Jos' },
    JDG: { name: 'Richter',                 abbreviation: 'Ri' },
    RUT: { name: 'Rut',                     abbreviation: 'Rut' },
    '1SA': { name: '1. Samuel',             abbreviation: '1.Sam' },
    '2SA': { name: '2. Samuel',             abbreviation: '2.Sam' },
    '1KI': { name: '1. Könige',             abbreviation: '1.Kön' },
    '2KI': { name: '2. Könige',             abbreviation: '2.Kön' },
    '1CH': { name: '1. Chronik',            abbreviation: '1.Chr' },
    '2CH': { name: '2. Chronik',            abbreviation: '2.Chr' },
    EZR: { name: 'Esra',                    abbreviation: 'Esra' },
    NEH: { name: 'Nehemia',                 abbreviation: 'Neh' },
    EST: { name: 'Ester',                   abbreviation: 'Est' },
    JOB: { name: 'Hiob',                    abbreviation: 'Hi' },
    PSA: { name: 'Psalmen',                 abbreviation: 'Ps' },
    PRO: { name: 'Sprüche',                 abbreviation: 'Spr' },
    ECC: { name: 'Prediger',                abbreviation: 'Pred' },
    SOL: { name: 'Hohelied',                abbreviation: 'Hl' },
    ISA: { name: 'Jesaja',                  abbreviation: 'Jes' },
    JER: { name: 'Jeremia',                 abbreviation: 'Jer' },
    LAM: { name: 'Klagelieder',             abbreviation: 'Kla' },
    EZE: { name: 'Hesekiel',                abbreviation: 'Hes' },
    DAN: { name: 'Daniel',                  abbreviation: 'Dan' },
    HOS: { name: 'Hosea',                   abbreviation: 'Hos' },
    JOE: { name: 'Joel',                    abbreviation: 'Joel' },
    AMO: { name: 'Amos',                    abbreviation: 'Am' },
    OBA: { name: 'Obadja',                  abbreviation: 'Obd' },
    JON: { name: 'Jona',                    abbreviation: 'Jona' },
    MIC: { name: 'Micha',                   abbreviation: 'Mi' },
    NAH: { name: 'Nahum',                   abbreviation: 'Nah' },
    HAB: { name: 'Habakuk',                 abbreviation: 'Hab' },
    ZEP: { name: 'Zefanja',                 abbreviation: 'Zef' },
    HAG: { name: 'Haggai',                  abbreviation: 'Hag' },
    ZEC: { name: 'Sacharja',                abbreviation: 'Sach' },
    MAL: { name: 'Maleachi',                abbreviation: 'Mal' },
    MAT: { name: 'Matthäus',                abbreviation: 'Mt' },
    MAR: { name: 'Markus',                  abbreviation: 'Mk' },
    LUK: { name: 'Lukas',                   abbreviation: 'Lk' },
    JOH: { name: 'Johannes',                abbreviation: 'Joh' },
    ACT: { name: 'Apostelgeschichte',       abbreviation: 'Apg' },
    ROM: { name: 'Römer',                   abbreviation: 'Röm' },
    '1CO': { name: '1. Korinther',          abbreviation: '1.Kor' },
    '2CO': { name: '2. Korinther',          abbreviation: '2.Kor' },
    GAL: { name: 'Galater',                 abbreviation: 'Gal' },
    EPH: { name: 'Epheser',                 abbreviation: 'Eph' },
    PHI: { name: 'Philipper',               abbreviation: 'Phil' },
    COL: { name: 'Kolosser',                abbreviation: 'Kol' },
    '1TH': { name: '1. Thessalonicher',     abbreviation: '1.Thess' },
    '2TH': { name: '2. Thessalonicher',     abbreviation: '2.Thess' },
    '1TI': { name: '1. Timotheus',          abbreviation: '1.Tim' },
    '2TI': { name: '2. Timotheus',          abbreviation: '2.Tim' },
    TIT: { name: 'Titus',                   abbreviation: 'Tit' },
    PHM: { name: 'Philemon',                abbreviation: 'Phlm' },
    HEB: { name: 'Hebräer',                 abbreviation: 'Hebr' },
    JAM: { name: 'Jakobus',                 abbreviation: 'Jak' },
    '1PE': { name: '1. Petrus',             abbreviation: '1.Petr' },
    '2PE': { name: '2. Petrus',             abbreviation: '2.Petr' },
    '1JO': { name: '1. Johannes',           abbreviation: '1.Joh' },
    '2JO': { name: '2. Johannes',           abbreviation: '2.Joh' },
    '3JO': { name: '3. Johannes',           abbreviation: '3.Joh' },
    JUD: { name: 'Judas',                   abbreviation: 'Jud' },
    REV: { name: 'Offenbarung',             abbreviation: 'Offb' },
  },
  en: {
    GEN: { name: 'Genesis',                 abbreviation: 'Gen' },
    EXO: { name: 'Exodus',                  abbreviation: 'Exo' },
    LEV: { name: 'Leviticus',               abbreviation: 'Lev' },
    NUM: { name: 'Numbers',                 abbreviation: 'Num' },
    DEU: { name: 'Deuteronomy',             abbreviation: 'Deu' },
    JOS: { name: 'Joshua',                  abbreviation: 'Jos' },
    JDG: { name: 'Judges',                  abbreviation: 'Jdg' },
    RUT: { name: 'Ruth',                    abbreviation: 'Rut' },
    '1SA': { name: '1 Samuel',              abbreviation: '1Sa' },
    '2SA': { name: '2 Samuel',              abbreviation: '2Sa' },
    '1KI': { name: '1 Kings',               abbreviation: '1Ki' },
    '2KI': { name: '2 Kings',               abbreviation: '2Ki' },
    '1CH': { name: '1 Chronicles',          abbreviation: '1Ch' },
    '2CH': { name: '2 Chronicles',          abbreviation: '2Ch' },
    EZR: { name: 'Ezra',                    abbreviation: 'Ezr' },
    NEH: { name: 'Nehemiah',                abbreviation: 'Neh' },
    EST: { name: 'Esther',                  abbreviation: 'Est' },
    JOB: { name: 'Job',                     abbreviation: 'Job' },
    PSA: { name: 'Psalms',                  abbreviation: 'Psa' },
    PRO: { name: 'Proverbs',                abbreviation: 'Pro' },
    ECC: { name: 'Ecclesiastes',            abbreviation: 'Ecc' },
    SOL: { name: 'Song of Solomon',         abbreviation: 'Sol' },
    ISA: { name: 'Isaiah',                  abbreviation: 'Isa' },
    JER: { name: 'Jeremiah',                abbreviation: 'Jer' },
    LAM: { name: 'Lamentations',            abbreviation: 'Lam' },
    EZE: { name: 'Ezekiel',                 abbreviation: 'Eze' },
    DAN: { name: 'Daniel',                  abbreviation: 'Dan' },
    HOS: { name: 'Hosea',                   abbreviation: 'Hos' },
    JOE: { name: 'Joel',                    abbreviation: 'Joe' },
    AMO: { name: 'Amos',                    abbreviation: 'Amo' },
    OBA: { name: 'Obadiah',                 abbreviation: 'Oba' },
    JON: { name: 'Jonah',                   abbreviation: 'Jon' },
    MIC: { name: 'Micah',                   abbreviation: 'Mic' },
    NAH: { name: 'Nahum',                   abbreviation: 'Nah' },
    HAB: { name: 'Habakkuk',                abbreviation: 'Hab' },
    ZEP: { name: 'Zephaniah',               abbreviation: 'Zep' },
    HAG: { name: 'Haggai',                  abbreviation: 'Hag' },
    ZEC: { name: 'Zechariah',               abbreviation: 'Zec' },
    MAL: { name: 'Malachi',                 abbreviation: 'Mal' },
    MAT: { name: 'Matthew',                 abbreviation: 'Mat' },
    MAR: { name: 'Mark',                    abbreviation: 'Mar' },
    LUK: { name: 'Luke',                    abbreviation: 'Luk' },
    JOH: { name: 'John',                    abbreviation: 'Joh' },
    ACT: { name: 'Acts',                    abbreviation: 'Act' },
    ROM: { name: 'Romans',                  abbreviation: 'Rom' },
    '1CO': { name: '1 Corinthians',         abbreviation: '1Co' },
    '2CO': { name: '2 Corinthians',         abbreviation: '2Co' },
    GAL: { name: 'Galatians',               abbreviation: 'Gal' },
    EPH: { name: 'Ephesians',               abbreviation: 'Eph' },
    PHI: { name: 'Philippians',             abbreviation: 'Phi' },
    COL: { name: 'Colossians',              abbreviation: 'Col' },
    '1TH': { name: '1 Thessalonians',       abbreviation: '1Th' },
    '2TH': { name: '2 Thessalonians',       abbreviation: '2Th' },
    '1TI': { name: '1 Timothy',             abbreviation: '1Ti' },
    '2TI': { name: '2 Timothy',             abbreviation: '2Ti' },
    TIT: { name: 'Titus',                   abbreviation: 'Tit' },
    PHM: { name: 'Philemon',                abbreviation: 'Phm' },
    HEB: { name: 'Hebrews',                 abbreviation: 'Heb' },
    JAM: { name: 'James',                   abbreviation: 'Jam' },
    '1PE': { name: '1 Peter',               abbreviation: '1Pe' },
    '2PE': { name: '2 Peter',               abbreviation: '2Pe' },
    '1JO': { name: '1 John',                abbreviation: '1Jo' },
    '2JO': { name: '2 John',                abbreviation: '2Jo' },
    '3JO': { name: '3 John',                abbreviation: '3Jo' },
    JUD: { name: 'Jude',                    abbreviation: 'Jud' },
    REV: { name: 'Revelation',              abbreviation: 'Rev' },
  },
};
