blank_issues_enabled: false
contact_links:
  - name: "💬 Questions or feedback?"
    url: https://github.com/theDeniZ/sdarm.life/discussions
    about: Use discussions for questions that aren't bugs or features
