/**
 * Localized book names and abbreviations, keyed by USFM code.
 *
 * The source JSON files carry no book names at all — only `Gen.1.1` keys — so
 * every name the reader sees comes from this table. One table per language, not
 * per translation: the six texts split into four languages and each language's
 * naming convention is shared by the translations in it (both German texts use
 * the Luther "1. Mose" convention; there is no second Russian or Spanish text).
 *
 * The abbreviations are the conventional short forms of each tradition — Loccum
 * for German, the usual SBL-ish short forms for English, the Synodal forms for
 * Russian, the Reina-Valera forms for Spanish. They are what the breadcrumb and
 * the passage picker show, so they must be recognisable, not merely unique.
 */

export interface BookName {
  name: string;
  abbreviation: string;
}

export type BookNameTable = Record<string, BookName>;

const de: BookNameTable = {
  GEN: { name: '1. Mose', abbreviation: '1Mo' },
  EXO: { name: '2. Mose', abbreviation: '2Mo' },
  LEV: { name: '3. Mose', abbreviation: '3Mo' },
  NUM: { name: '4. Mose', abbreviation: '4Mo' },
  DEU: { name: '5. Mose', abbreviation: '5Mo' },
  JOS: { name: 'Josua', abbreviation: 'Jos' },
  JDG: { name: 'Richter', abbreviation: 'Ri' },
  RUT: { name: 'Rut', abbreviation: 'Rut' },
  '1SA': { name: '1. Samuel', abbreviation: '1Sam' },
  '2SA': { name: '2. Samuel', abbreviation: '2Sam' },
  '1KI': { name: '1. Könige', abbreviation: '1Kön' },
  '2KI': { name: '2. Könige', abbreviation: '2Kön' },
  '1CH': { name: '1. Chronik', abbreviation: '1Chr' },
  '2CH': { name: '2. Chronik', abbreviation: '2Chr' },
  EZR: { name: 'Esra', abbreviation: 'Esr' },
  NEH: { name: 'Nehemia', abbreviation: 'Neh' },
  EST: { name: 'Ester', abbreviation: 'Est' },
  JOB: { name: 'Hiob', abbreviation: 'Hi' },
  PSA: { name: 'Psalmen', abbreviation: 'Ps' },
  PRO: { name: 'Sprüche', abbreviation: 'Spr' },
  ECC: { name: 'Prediger', abbreviation: 'Pred' },
  SNG: { name: 'Hoheslied', abbreviation: 'Hld' },
  ISA: { name: 'Jesaja', abbreviation: 'Jes' },
  JER: { name: 'Jeremia', abbreviation: 'Jer' },
  LAM: { name: 'Klagelieder', abbreviation: 'Klgl' },
  EZK: { name: 'Hesekiel', abbreviation: 'Hes' },
  DAN: { name: 'Daniel', abbreviation: 'Dan' },
  HOS: { name: 'Hosea', abbreviation: 'Hos' },
  JOL: { name: 'Joel', abbreviation: 'Joel' },
  AMO: { name: 'Amos', abbreviation: 'Am' },
  OBA: { name: 'Obadja', abbreviation: 'Obd' },
  JON: { name: 'Jona', abbreviation: 'Jona' },
  MIC: { name: 'Micha', abbreviation: 'Mi' },
  NAM: { name: 'Nahum', abbreviation: 'Nah' },
  HAB: { name: 'Habakuk', abbreviation: 'Hab' },
  ZEP: { name: 'Zefanja', abbreviation: 'Zef' },
  HAG: { name: 'Haggai', abbreviation: 'Hag' },
  ZEC: { name: 'Sacharja', abbreviation: 'Sach' },
  MAL: { name: 'Maleachi', abbreviation: 'Mal' },
  MAT: { name: 'Matthäus', abbreviation: 'Mt' },
  MRK: { name: 'Markus', abbreviation: 'Mk' },
  LUK: { name: 'Lukas', abbreviation: 'Lk' },
  JHN: { name: 'Johannes', abbreviation: 'Joh' },
  ACT: { name: 'Apostelgeschichte', abbreviation: 'Apg' },
  ROM: { name: 'Römer', abbreviation: 'Röm' },
  '1CO': { name: '1. Korinther', abbreviation: '1Kor' },
  '2CO': { name: '2. Korinther', abbreviation: '2Kor' },
  GAL: { name: 'Galater', abbreviation: 'Gal' },
  EPH: { name: 'Epheser', abbreviation: 'Eph' },
  PHP: { name: 'Philipper', abbreviation: 'Phil' },
  COL: { name: 'Kolosser', abbreviation: 'Kol' },
  '1TH': { name: '1. Thessalonicher', abbreviation: '1Thess' },
  '2TH': { name: '2. Thessalonicher', abbreviation: '2Thess' },
  '1TI': { name: '1. Timotheus', abbreviation: '1Tim' },
  '2TI': { name: '2. Timotheus', abbreviation: '2Tim' },
  TIT: { name: 'Titus', abbreviation: 'Tit' },
  PHM: { name: 'Philemon', abbreviation: 'Phlm' },
  HEB: { name: 'Hebräer', abbreviation: 'Hebr' },
  JAS: { name: 'Jakobus', abbreviation: 'Jak' },
  '1PE': { name: '1. Petrus', abbreviation: '1Petr' },
  '2PE': { name: '2. Petrus', abbreviation: '2Petr' },
  '1JN': { name: '1. Johannes', abbreviation: '1Joh' },
  '2JN': { name: '2. Johannes', abbreviation: '2Joh' },
  '3JN': { name: '3. Johannes', abbreviation: '3Joh' },
  JUD: { name: 'Judas', abbreviation: 'Jud' },
  REV: { name: 'Offenbarung', abbreviation: 'Offb' },
};

const en: BookNameTable = {
  GEN: { name: 'Genesis', abbreviation: 'Gen' },
  EXO: { name: 'Exodus', abbreviation: 'Ex' },
  LEV: { name: 'Leviticus', abbreviation: 'Lev' },
  NUM: { name: 'Numbers', abbreviation: 'Num' },
  DEU: { name: 'Deuteronomy', abbreviation: 'Deut' },
  JOS: { name: 'Joshua', abbreviation: 'Josh' },
  JDG: { name: 'Judges', abbreviation: 'Judg' },
  RUT: { name: 'Ruth', abbreviation: 'Ruth' },
  '1SA': { name: '1 Samuel', abbreviation: '1 Sam' },
  '2SA': { name: '2 Samuel', abbreviation: '2 Sam' },
  '1KI': { name: '1 Kings', abbreviation: '1 Kgs' },
  '2KI': { name: '2 Kings', abbreviation: '2 Kgs' },
  '1CH': { name: '1 Chronicles', abbreviation: '1 Chr' },
  '2CH': { name: '2 Chronicles', abbreviation: '2 Chr' },
  EZR: { name: 'Ezra', abbreviation: 'Ezra' },
  NEH: { name: 'Nehemiah', abbreviation: 'Neh' },
  EST: { name: 'Esther', abbreviation: 'Esth' },
  JOB: { name: 'Job', abbreviation: 'Job' },
  PSA: { name: 'Psalms', abbreviation: 'Ps' },
  PRO: { name: 'Proverbs', abbreviation: 'Prov' },
  ECC: { name: 'Ecclesiastes', abbreviation: 'Eccl' },
  SNG: { name: 'Song of Solomon', abbreviation: 'Song' },
  ISA: { name: 'Isaiah', abbreviation: 'Isa' },
  JER: { name: 'Jeremiah', abbreviation: 'Jer' },
  LAM: { name: 'Lamentations', abbreviation: 'Lam' },
  EZK: { name: 'Ezekiel', abbreviation: 'Ezek' },
  DAN: { name: 'Daniel', abbreviation: 'Dan' },
  HOS: { name: 'Hosea', abbreviation: 'Hos' },
  JOL: { name: 'Joel', abbreviation: 'Joel' },
  AMO: { name: 'Amos', abbreviation: 'Amos' },
  OBA: { name: 'Obadiah', abbreviation: 'Obad' },
  JON: { name: 'Jonah', abbreviation: 'Jonah' },
  MIC: { name: 'Micah', abbreviation: 'Mic' },
  NAM: { name: 'Nahum', abbreviation: 'Nah' },
  HAB: { name: 'Habakkuk', abbreviation: 'Hab' },
  ZEP: { name: 'Zephaniah', abbreviation: 'Zeph' },
  HAG: { name: 'Haggai', abbreviation: 'Hag' },
  ZEC: { name: 'Zechariah', abbreviation: 'Zech' },
  MAL: { name: 'Malachi', abbreviation: 'Mal' },
  MAT: { name: 'Matthew', abbreviation: 'Matt' },
  MRK: { name: 'Mark', abbreviation: 'Mark' },
  LUK: { name: 'Luke', abbreviation: 'Luke' },
  JHN: { name: 'John', abbreviation: 'John' },
  ACT: { name: 'Acts', abbreviation: 'Acts' },
  ROM: { name: 'Romans', abbreviation: 'Rom' },
  '1CO': { name: '1 Corinthians', abbreviation: '1 Cor' },
  '2CO': { name: '2 Corinthians', abbreviation: '2 Cor' },
  GAL: { name: 'Galatians', abbreviation: 'Gal' },
  EPH: { name: 'Ephesians', abbreviation: 'Eph' },
  PHP: { name: 'Philippians', abbreviation: 'Phil' },
  COL: { name: 'Colossians', abbreviation: 'Col' },
  '1TH': { name: '1 Thessalonians', abbreviation: '1 Thess' },
  '2TH': { name: '2 Thessalonians', abbreviation: '2 Thess' },
  '1TI': { name: '1 Timothy', abbreviation: '1 Tim' },
  '2TI': { name: '2 Timothy', abbreviation: '2 Tim' },
  TIT: { name: 'Titus', abbreviation: 'Titus' },
  PHM: { name: 'Philemon', abbreviation: 'Phlm' },
  HEB: { name: 'Hebrews', abbreviation: 'Heb' },
  JAS: { name: 'James', abbreviation: 'Jas' },
  '1PE': { name: '1 Peter', abbreviation: '1 Pet' },
  '2PE': { name: '2 Peter', abbreviation: '2 Pet' },
  '1JN': { name: '1 John', abbreviation: '1 John' },
  '2JN': { name: '2 John', abbreviation: '2 John' },
  '3JN': { name: '3 John', abbreviation: '3 John' },
  JUD: { name: 'Jude', abbreviation: 'Jude' },
  REV: { name: 'Revelation', abbreviation: 'Rev' },
};

// Synodal naming: the four books of Kingdoms — 1/2 Samuel are 1-я/2-я Царств and
// 1/2 Kings are 3-я/4-я Царств. Getting that pair wrong is the classic error.
const ru: BookNameTable = {
  GEN: { name: 'Бытие', abbreviation: 'Быт' },
  EXO: { name: 'Исход', abbreviation: 'Исх' },
  LEV: { name: 'Левит', abbreviation: 'Лев' },
  NUM: { name: 'Числа', abbreviation: 'Чис' },
  DEU: { name: 'Второзаконие', abbreviation: 'Втор' },
  JOS: { name: 'Иисус Навин', abbreviation: 'Нав' },
  JDG: { name: 'Книга Судей', abbreviation: 'Суд' },
  RUT: { name: 'Руфь', abbreviation: 'Руф' },
  '1SA': { name: '1-я Царств', abbreviation: '1Цар' },
  '2SA': { name: '2-я Царств', abbreviation: '2Цар' },
  '1KI': { name: '3-я Царств', abbreviation: '3Цар' },
  '2KI': { name: '4-я Царств', abbreviation: '4Цар' },
  '1CH': { name: '1-я Паралипоменон', abbreviation: '1Пар' },
  '2CH': { name: '2-я Паралипоменон', abbreviation: '2Пар' },
  EZR: { name: 'Ездра', abbreviation: 'Езд' },
  NEH: { name: 'Неемия', abbreviation: 'Неем' },
  EST: { name: 'Есфирь', abbreviation: 'Есф' },
  JOB: { name: 'Иов', abbreviation: 'Иов' },
  PSA: { name: 'Псалтирь', abbreviation: 'Пс' },
  PRO: { name: 'Притчи', abbreviation: 'Притч' },
  ECC: { name: 'Екклесиаст', abbreviation: 'Еккл' },
  SNG: { name: 'Песнь Песней', abbreviation: 'Песн' },
  ISA: { name: 'Исаия', abbreviation: 'Ис' },
  JER: { name: 'Иеремия', abbreviation: 'Иер' },
  LAM: { name: 'Плач Иеремии', abbreviation: 'Плач' },
  EZK: { name: 'Иезекииль', abbreviation: 'Иез' },
  DAN: { name: 'Даниил', abbreviation: 'Дан' },
  HOS: { name: 'Осия', abbreviation: 'Ос' },
  JOL: { name: 'Иоиль', abbreviation: 'Иоил' },
  AMO: { name: 'Амос', abbreviation: 'Ам' },
  OBA: { name: 'Авдий', abbreviation: 'Авд' },
  JON: { name: 'Иона', abbreviation: 'Ион' },
  MIC: { name: 'Михей', abbreviation: 'Мих' },
  NAM: { name: 'Наум', abbreviation: 'Наум' },
  HAB: { name: 'Аввакум', abbreviation: 'Авв' },
  ZEP: { name: 'Софония', abbreviation: 'Соф' },
  HAG: { name: 'Аггей', abbreviation: 'Агг' },
  ZEC: { name: 'Захария', abbreviation: 'Зах' },
  MAL: { name: 'Малахия', abbreviation: 'Мал' },
  MAT: { name: 'От Матфея', abbreviation: 'Мф' },
  MRK: { name: 'От Марка', abbreviation: 'Мк' },
  LUK: { name: 'От Луки', abbreviation: 'Лк' },
  JHN: { name: 'От Иоанна', abbreviation: 'Ин' },
  ACT: { name: 'Деяния', abbreviation: 'Деян' },
  ROM: { name: 'К Римлянам', abbreviation: 'Рим' },
  '1CO': { name: '1-е Коринфянам', abbreviation: '1Кор' },
  '2CO': { name: '2-е Коринфянам', abbreviation: '2Кор' },
  GAL: { name: 'К Галатам', abbreviation: 'Гал' },
  EPH: { name: 'К Ефесянам', abbreviation: 'Еф' },
  PHP: { name: 'К Филиппийцам', abbreviation: 'Флп' },
  COL: { name: 'К Колоссянам', abbreviation: 'Кол' },
  '1TH': { name: '1-е Фессалоникийцам', abbreviation: '1Фес' },
  '2TH': { name: '2-е Фессалоникийцам', abbreviation: '2Фес' },
  '1TI': { name: '1-е Тимофею', abbreviation: '1Тим' },
  '2TI': { name: '2-е Тимофею', abbreviation: '2Тим' },
  TIT: { name: 'К Титу', abbreviation: 'Тит' },
  PHM: { name: 'К Филимону', abbreviation: 'Флм' },
  HEB: { name: 'К Евреям', abbreviation: 'Евр' },
  JAS: { name: 'Иакова', abbreviation: 'Иак' },
  '1PE': { name: '1-е Петра', abbreviation: '1Пет' },
  '2PE': { name: '2-е Петра', abbreviation: '2Пет' },
  '1JN': { name: '1-е Иоанна', abbreviation: '1Ин' },
  '2JN': { name: '2-е Иоанна', abbreviation: '2Ин' },
  '3JN': { name: '3-е Иоанна', abbreviation: '3Ин' },
  JUD: { name: 'Иуды', abbreviation: 'Иуд' },
  REV: { name: 'Откровение', abbreviation: 'Откр' },
};

const es: BookNameTable = {
  GEN: { name: 'Génesis', abbreviation: 'Gn' },
  EXO: { name: 'Éxodo', abbreviation: 'Éx' },
  LEV: { name: 'Levítico', abbreviation: 'Lv' },
  NUM: { name: 'Números', abbreviation: 'Nm' },
  DEU: { name: 'Deuteronomio', abbreviation: 'Dt' },
  JOS: { name: 'Josué', abbreviation: 'Jos' },
  JDG: { name: 'Jueces', abbreviation: 'Jue' },
  RUT: { name: 'Rut', abbreviation: 'Rt' },
  '1SA': { name: '1 Samuel', abbreviation: '1 S' },
  '2SA': { name: '2 Samuel', abbreviation: '2 S' },
  '1KI': { name: '1 Reyes', abbreviation: '1 R' },
  '2KI': { name: '2 Reyes', abbreviation: '2 R' },
  '1CH': { name: '1 Crónicas', abbreviation: '1 Cr' },
  '2CH': { name: '2 Crónicas', abbreviation: '2 Cr' },
  EZR: { name: 'Esdras', abbreviation: 'Esd' },
  NEH: { name: 'Nehemías', abbreviation: 'Neh' },
  EST: { name: 'Ester', abbreviation: 'Est' },
  JOB: { name: 'Job', abbreviation: 'Job' },
  PSA: { name: 'Salmos', abbreviation: 'Sal' },
  PRO: { name: 'Proverbios', abbreviation: 'Pr' },
  ECC: { name: 'Eclesiastés', abbreviation: 'Ec' },
  SNG: { name: 'Cantares', abbreviation: 'Cnt' },
  ISA: { name: 'Isaías', abbreviation: 'Is' },
  JER: { name: 'Jeremías', abbreviation: 'Jer' },
  LAM: { name: 'Lamentaciones', abbreviation: 'Lm' },
  EZK: { name: 'Ezequiel', abbreviation: 'Ez' },
  DAN: { name: 'Daniel', abbreviation: 'Dn' },
  HOS: { name: 'Oseas', abbreviation: 'Os' },
  JOL: { name: 'Joel', abbreviation: 'Jl' },
  AMO: { name: 'Amós', abbreviation: 'Am' },
  OBA: { name: 'Abdías', abbreviation: 'Abd' },
  JON: { name: 'Jonás', abbreviation: 'Jon' },
  MIC: { name: 'Miqueas', abbreviation: 'Mi' },
  NAM: { name: 'Nahúm', abbreviation: 'Nah' },
  HAB: { name: 'Habacuc', abbreviation: 'Hab' },
  ZEP: { name: 'Sofonías', abbreviation: 'Sof' },
  HAG: { name: 'Hageo', abbreviation: 'Hag' },
  ZEC: { name: 'Zacarías', abbreviation: 'Zac' },
  MAL: { name: 'Malaquías', abbreviation: 'Mal' },
  MAT: { name: 'Mateo', abbreviation: 'Mt' },
  MRK: { name: 'Marcos', abbreviation: 'Mr' },
  LUK: { name: 'Lucas', abbreviation: 'Lc' },
  JHN: { name: 'Juan', abbreviation: 'Jn' },
  ACT: { name: 'Hechos', abbreviation: 'Hch' },
  ROM: { name: 'Romanos', abbreviation: 'Ro' },
  '1CO': { name: '1 Corintios', abbreviation: '1 Co' },
  '2CO': { name: '2 Corintios', abbreviation: '2 Co' },
  GAL: { name: 'Gálatas', abbreviation: 'Gá' },
  EPH: { name: 'Efesios', abbreviation: 'Ef' },
  PHP: { name: 'Filipenses', abbreviation: 'Fil' },
  COL: { name: 'Colosenses', abbreviation: 'Col' },
  '1TH': { name: '1 Tesalonicenses', abbreviation: '1 Ts' },
  '2TH': { name: '2 Tesalonicenses', abbreviation: '2 Ts' },
  '1TI': { name: '1 Timoteo', abbreviation: '1 Ti' },
  '2TI': { name: '2 Timoteo', abbreviation: '2 Ti' },
  TIT: { name: 'Tito', abbreviation: 'Tit' },
  PHM: { name: 'Filemón', abbreviation: 'Flm' },
  HEB: { name: 'Hebreos', abbreviation: 'He' },
  JAS: { name: 'Santiago', abbreviation: 'Stg' },
  '1PE': { name: '1 Pedro', abbreviation: '1 P' },
  '2PE': { name: '2 Pedro', abbreviation: '2 P' },
  '1JN': { name: '1 Juan', abbreviation: '1 Jn' },
  '2JN': { name: '2 Juan', abbreviation: '2 Jn' },
  '3JN': { name: '3 Juan', abbreviation: '3 Jn' },
  JUD: { name: 'Judas', abbreviation: 'Jud' },
  REV: { name: 'Apocalipsis', abbreviation: 'Ap' },
};

export const BOOK_NAMES: Record<string, BookNameTable> = { de, en, ru, es };

export function bookName(language: string, usfm: string): BookName {
  const table = BOOK_NAMES[language];
  if (!table) throw new Error(`No book-name table for language '${language}' — add one to scripts/bible/bookNames.ts.`);
  const entry = table[usfm];
  if (!entry) throw new Error(`No '${language}' name for book '${usfm}' — the table is incomplete.`);
  return entry;
}
